### ISSUE TITLE
Add support for a config file (.grcrc maybe?)

### ISSUE THREAD

**Issue by eXigentCoder** [JPStrydom/Generate-React-Code#2]
Looks great, would be awesome if you could store some default options in a file (.grcrc maybe?) in your project so that you don't need to pass them in to the command line each time.

**Comment by JPStrydom** [comment]
Sounds like a really good idea! Will get started on it soon :neckbeard:

**Comment by JPStrydom** [comment]
I added this in the last release. Let me know what you think @eXigentCoder

**Comment by JPStrydom** [comment]
Closed by #3
